- name: "Get ScaleIO token for Auth"
  uri:
    url: https://10.237.198.170/api/login 
    return_content: yes
    user: admin
    password: "Password#1"
    force_basic_auth: yes
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  register: msg
- debug:
    var: msg.json


- name: "Query Protection Domain pd1"
  uri:
    url: https://10.237.198.170/api/types/ProtectionDomain/instances
    method: GET
    user: admin
    password: "{{ msg.json }}"
    return_content: yes
    force_basic_auth: yes
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  register: protection_domain_id
  ignore_errors: yes

- debug:
    var: protection_domain_id.json[0].id


- name: "Add SDS Server to Storage Pool SP1"
  uri:
    url: https://10.237.198.170/api/types/Sds/instances 
    method: POST
    user: admin
    password: "{{ msg.json }}"
    body: {"protectionDomainId": "{{ protection_domain_id.json[0].id }}", "sdsIpList": [{"SdsIp": {"ip": "192.168.10.203", "role": "all"}}],"name": "terraform-SIOSVM3"}
    force_basic_auth: yes
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
    ignore_errors: yes
